import type { Resource } from "@/types/resource";

export const fakeResources: Resource[] = [
  {
    id: "short-vowels-week-1",
    slug: "short-vowels-week-1",
    title: "Short Vowels - Week 1",
    description: "A first grade ELA resource pack for short vowel practice.",
    grade: "First Grade",
    subject: "ELA",
    week: 1,
    standard: "RF.1.2",
    category: "Lesson Plan",
    thumbnail: "",
    pdf: "",
    featured: true,
    status: "published",
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "sight-words-week-1",
    slug: "sight-words-week-1",
    title: "Sight Words - Week 1",
    description: "Practice pages, small group activities, and review cards.",
    grade: "First Grade",
    subject: "ELA",
    week: 1,
    standard: "RF.1.3",
    category: "Activity",
    thumbnail: "",
    pdf: "",
    featured: false,
    status: "published",
    createdAt: "2026-06-02T12:00:00.000Z",
    updatedAt: "2026-06-17T12:00:00.000Z",
  },
  {
    id: "addition-week-1",
    slug: "addition-week-1",
    title: "Addition Within 10 - Week 1",
    description: "Ready-to-use math activities and practice pages.",
    grade: "First Grade",
    subject: "Math",
    week: 1,
    standard: "1.OA.C.6",
    category: "Homework",
    thumbnail: "",
    pdf: "",
    featured: false,
    status: "published",
    createdAt: "2026-06-03T12:00:00.000Z",
    updatedAt: "2026-06-16T12:00:00.000Z",
  },
  {
    id: "plants-week-2",
    slug: "plants-week-2",
    title: "Plant Life Cycle - Week 2",
    description: "Science lesson plan with vocabulary, activity, and assessment.",
    grade: "First Grade",
    subject: "Science",
    week: 2,
    standard: "1.L.1",
    category: "Lesson Plan",
    thumbnail: "",
    pdf: "",
    featured: true,
    status: "published",
    createdAt: "2026-06-04T12:00:00.000Z",
    updatedAt: "2026-06-20T12:00:00.000Z",
  },
  {
    id: "community-helpers-week-2",
    slug: "community-helpers-week-2",
    title: "Community Helpers - Week 2",
    description: "Social studies activities about roles in the community.",
    grade: "First Grade",
    subject: "Social Studies",
    week: 2,
    standard: "1.C&G.1",
    category: "Centers",
    thumbnail: "",
    pdf: "",
    featured: false,
    status: "draft",
    createdAt: "2026-06-05T12:00:00.000Z",
    updatedAt: "2026-06-19T12:00:00.000Z",
  },
];
