import type { Resource } from "@/types/resource";

export const resources: Resource[] = [
  {
    id: "short-vowels-week-1",
    title: "Short Vowels - Week 1",
    description: "A first grade ELA resource pack for short vowel practice.",
    grade: "First Grade",
    subject: "ELA",
    week: 1,
    standard: "RF.1.2",
    category: "Lesson Plan",
    thumbnail: "",
    pdf: "",
    featured: true,
  },
  {
    id: "sight-words-week-1",
    title: "Sight Words - Week 1",
    description: "Practice pages, small group activities, and review cards.",
    grade: "First Grade",
    subject: "ELA",
    week: 1,
    standard: "RF.1.3",
    category: "Worksheet",
    thumbnail: "",
    pdf: "",
    featured: false,
  },
  {
    id: "addition-week-1",
    title: "Addition Within 10 - Week 1",
    description: "Ready-to-use math activities and practice pages.",
    grade: "First Grade",
    subject: "Math",
    week: 1,
    standard: "1.OA.C.6",
    category: "Worksheet",
    thumbnail: "",
    pdf: "",
    featured: false,
  },
  {
    id: "plants-week-2",
    title: "Plant Life Cycle - Week 2",
    description: "Science lesson plan with vocabulary, activity, and assessment.",
    grade: "First Grade",
    subject: "Science",
    week: 2,
    standard: "1.L.1",
    category: "Lesson Plan",
    thumbnail: "",
    pdf: "",
    featured: true,
  },
  {
    id: "community-helpers-week-2",
    title: "Community Helpers - Week 2",
    description: "Social studies activities about roles in the community.",
    grade: "First Grade",
    subject: "Social Studies",
    week: 2,
    standard: "1.C&G.1",
    category: "Center",
    thumbnail: "",
    pdf: "",
    featured: false,
  },
];